#!/usr/bin/env bash
# test-kb-scanner-exclusions.sh -- work-011 smart scope refinement for the two KB
# scanners (harvest-coined-terms.sh + build-project-index.sh). Beyond the static
# SKIP_DIRS dir-prune, both scanners now drop non-source FILES via DETERMINISTIC,
# git-native, machine-neutralized checks (so output stays byte-reproducible):
#   - minified bundles / sourcemaps  (*.min.js, *.min.css, *.map)
#   - .gitignore'd files             (committed rules only; global excludes off)
#   - .gitattributes linguist-generated / linguist-vendored (NOT documentation)
#   - @generated / DO NOT EDIT header markers (first 2 lines)
# plus the expanded SKIP_DIRS (.venv, coverage, logs, ...).
#
#   E01  build-index drops minified/sourcemap, gitignored, generated/vendored,
#        @generated-header, and expanded-SKIP_DIRS paths
#   E02  build-index STILL indexes real source + docs (no over-prune)
#   E03  harvest candidate universe carries NONE of the noise tokens/paths
#   E04  harvest STILL surfaces a code term AND a docs-channel term (docs kept)
#   E05  non-git fallback: scanners still run; pattern excludes still apply
#
# Auto-discovered by tests/run-all.sh (glob tests/canonical/test-*.sh).
# Usage: bash tests/canonical/test-kb-scanner-exclusions.sh [--verbose]
# Exit codes: 0 all pass / 1 any fail.

set -u
VERBOSE=0
[[ "${1:-}" == "--verbose" ]] && VERBOSE=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${SCRIPT_DIR}/../.."
BPI="${REPO}/canonical/aid/scripts/kb/build-project-index.sh"
HARVEST="${REPO}/canonical/aid/scripts/kb/harvest-coined-terms.sh"
source "${SCRIPT_DIR}/../lib/assert.sh"
echo "== test-kb-scanner-exclusions.sh =="
for f in "$BPI" "$HARVEST"; do [[ -f "$f" ]] || { echo "FATAL: scanner not found: $f" >&2; exit 2; }; done
command -v git >/dev/null 2>&1 || { echo "SKIP: git not available"; exit 0; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# ---------------------------------------------------------------------------
# Build a git-repo fixture exercising every deterministic exclusion layer.
# Each noise file carries a unique token so any leakage is unmistakable.
# ---------------------------------------------------------------------------
FX="$TMP/proj"
mkdir -p "$FX/src" "$FX/docs" "$FX/gen" "$FX/third_party" "$FX/.venv" "$FX/coverage" "$FX/logs"
(
  cd "$FX"
  git init -q; git config user.email t@t.dev; git config user.name t
  # real source + docs (KEEP -- carry coined terms; docs is a harvest channel)
  printf '// WidgetEngine runs the FrobnicationPipeline.\nexport class WidgetEngine {}\n' > src/app.ts
  printf '# Readme\nThe WidgetEngine and FrobnicationPipeline are core.\n'               > README.md
  printf '# Guide\nDocChannelToken describes the FrobnicationPipeline.\n'                > docs/guide.md
  # minified + sourcemap (drop via pattern)
  printf 'var MinifiedOnlyToken=1;\n'   > src/bundle.min.js
  printf '{"MapOnlyToken":1}\n'         > src/app.js.map
  # @generated / DO NOT EDIT headers (drop)
  printf '// @generated by protoc\nexport const GeneratedHeaderToken=1;\n' > gen/schema.ts
  printf '// DO NOT EDIT\nexport const DoNotEditToken=1;\n'                 > src/machine.ts
  # .gitattributes linguist-generated / linguist-vendored (drop)
  printf 'gen/** linguist-generated=true\nthird_party/** linguist-vendored=true\n' > .gitattributes
  printf 'export const AttrGeneratedToken=1;\n' > gen/attr.ts
  printf 'export const VendoredToken=1;\n'      > third_party/lib.js
  # gitignored UNTRACKED file (drop via .gitignore; tracked files would NOT be dropped)
  printf 'build-artifact.ts\n'          > .gitignore
  printf 'export const GitignoredToken=1;\n' > build-artifact.ts
  # expanded SKIP_DIRS dirs (drop via dir-prune)
  printf 'VenvToken=1\n'   > .venv/pkg.py
  printf 'CoverageToken\n' > coverage/report.html
  printf 'LogToken\n'      > logs/run.log
  git add -A src docs gen third_party .gitattributes .gitignore README.md >/dev/null 2>&1
  git commit -qm init >/dev/null 2>&1
) || { echo "FATAL: fixture git setup failed" >&2; exit 2; }

IDX="$TMP/project-index.md"; CAND="$TMP/candidate-concepts.md"
bash "$BPI"     --root "$FX" --output "$IDX"  >/dev/null 2>&1
bash "$HARVEST" --root "$FX" --output "$CAND" >/dev/null 2>&1

# Every noise token/path that must NEVER appear in either output.
NOISE='MinifiedOnlyToken|MapOnlyToken|GeneratedHeaderToken|DoNotEditToken|AttrGeneratedToken|VendoredToken|GitignoredToken|VenvToken|CoverageToken|LogToken|bundle\.min\.js|\.js\.map|build-artifact|gen/|third_party/|\.venv/|coverage/|logs/'

# --- E01: project-index drops every noise class ---------------------------
if [[ -f "$IDX" ]] && grep -qE "$NOISE" "$IDX"; then
  fail "E01 project-index.md must exclude minified/gitignored/generated/vendored/@generated/skip-dir paths"
  [[ "$VERBOSE" -eq 1 ]] && grep -nE "$NOISE" "$IDX"
else
  pass "E01 project-index.md excludes all non-source noise (minified, .gitignore, linguist gen/vendor, @generated, expanded SKIP_DIRS)"
fi

# --- E02: real source + docs still indexed --------------------------------
if [[ -f "$IDX" ]] && grep -q 'src/app.ts' "$IDX" && grep -q 'docs/guide.md' "$IDX"; then
  pass "E02 project-index.md still indexes real source (src/app.ts) + docs (docs/guide.md)"
else
  fail "E02 project-index.md dropped real source or docs (over-prune)"
fi

# --- E03: harvest candidate universe carries no noise ---------------------
if [[ -f "$CAND" ]] && grep -qE "$NOISE" "$CAND"; then
  fail "E03 candidate-concepts.md must carry no noise token/path"
  [[ "$VERBOSE" -eq 1 ]] && grep -nE "$NOISE" "$CAND"
else
  pass "E03 candidate-concepts.md carries none of the excluded noise"
fi

# --- E04: code term AND docs-channel term survive (docs NOT over-pruned) ---
if [[ -f "$CAND" ]] && grep -qiE 'widget|frobnication' "$CAND" && grep -q 'DocChannelToken' "$CAND"; then
  pass "E04 candidate-concepts.md keeps a code term + a docs-channel term (linguist-documentation intentionally NOT pruned)"
else
  fail "E04 candidate-concepts.md lost the code term or the docs-channel term (over-prune)"
fi

# --- E05: non-git fallback -- scanners still run; pattern excludes apply ----
NG="$TMP/nogit"; mkdir -p "$NG/src"
printf 'export const PlainToken = 1;\n' > "$NG/src/app.ts"
printf 'var MinifiedOnlyToken2=1;\n'    > "$NG/src/x.min.js"
NGIDX="$TMP/ng-index.md"
if bash "$BPI" --root "$NG" --output "$NGIDX" >/dev/null 2>&1 && [[ -f "$NGIDX" ]]; then
  if grep -q 'src/app.ts' "$NGIDX" && ! grep -q 'x.min.js' "$NGIDX"; then
    pass "E05 non-git fallback: build-index runs, indexes source, still drops *.min.js (pattern excludes are git-independent)"
  else
    fail "E05 non-git fallback: expected source kept + minified dropped"
    [[ "$VERBOSE" -eq 1 ]] && cat "$NGIDX"
  fi
else
  fail "E05 non-git fallback: build-index failed on a non-git root"
fi

test_summary
