#!/usr/bin/env bash
# test-catalog-dirs-parity.sh -- task-010 (work-001-lite-aid-skills, feature-003 AC-1):
# the render-drift analog for the generated shortcut doorways.
#
# Asserts that every canonical/aid/templates/shortcut-catalog.yml row maps to EXACTLY ONE
# canonical/skills/<name>/SKILL.md directory:
#   - frontmatter `name:` == directory name == the row's own `name` field, `aid-` prefixed
#     (AC-1's mechanical proof)
#   - non-`repurpose` (thin-doorway) rows: the body binds the row's {verb, artifact} and
#     delegates to the shared engine (canonical/aid/templates/shortcut-engine.md)
#   - `repurpose: true` rows (the 4 pre-existing FAT pipeline/hand-authored skills, aid-deploy/aid-monitor/aid-query-kb/aid-ask)
#     are exempted to dir-exists + name-match + `aid-` prefix ONLY -- no body-content assertion
#     (feature-012 owns their bodies)
#   - no orphan directory (a GENERATED-marker doorway with no matching catalog row)
#   - no orphan row (every row's directory actually exists)
#
# Count-AGNOSTIC BY DESIGN: passes whether the catalog carries 1 row (today -- aid-fix,
# feature-008) or the full 80 (51 canonical + 29 alias). The full 80-row count assertion is
# task-035's own, separate test -- NOT duplicated here.
#
# Corroborating oracle: build-shortcut-skills.py --check (the maintainer helper's own byte-level
# drift detector) is also invoked as an independent cross-check on top of this suite's own
# hand-rolled AC-level parsing/assertions.
#
# Usage:
#   bash tests/canonical/test-catalog-dirs-parity.sh [--verbose]
# Exit codes: 0 all pass / 1 any fail.

set -uo pipefail

VERBOSE=0
[[ "${1:-}" =~ ^(-v|--verbose)$ ]] && VERBOSE=1

source "$(dirname "${BASH_SOURCE[0]}")/../lib/assert.sh"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CATALOG="${REPO_ROOT}/canonical/aid/templates/shortcut-catalog.yml"
SKILLS_ROOT="${REPO_ROOT}/canonical/skills"
BUILD_HELPER="${REPO_ROOT}/.claude/skills/generate-profile/scripts/build-shortcut-skills.py"
ENGINE_REF="canonical/aid/templates/shortcut-engine.md"
GENERATED_MARKER="<!-- GENERATED by .claude/skills/generate-profile/scripts/build-shortcut-skills.py"

echo "=== Catalog <-> skill-dirs parity (task-010, feature-003 AC-1) ==="

assert_file_exists "$CATALOG" "CDP00a shortcut-catalog.yml exists"
assert_dir_exists  "$SKILLS_ROOT" "CDP00b canonical/skills/ exists"
assert_file_exists "$BUILD_HELPER" "CDP00c build-shortcut-skills.py exists"

if [[ $FAIL -gt 0 ]]; then
    test_summary
    exit 1
fi

# ---------------------------------------------------------------------------
# Parse the catalog's `shortcuts:` rows into pipe-delimited records:
#   name|verb|artifact|alias_of|repurpose
# (a non-whitespace delimiter is required -- bash `read` collapses consecutive
# IFS-whitespace delimiters, which would silently swallow an empty `artifact` field)
#
# Restricted YAML subset (flat single-level mappings, one row per `- name:` line) --
# re-derived independently in awk (NOT by importing build-shortcut-skills.py's internals)
# so this test's own parity proof does not depend on the maintainer helper being correct.
# ---------------------------------------------------------------------------
ROWS_TSV=$(awk '
  BEGIN { in_ss = 0; name=""; verb=""; artifact=""; alias_of=""; repurpose="false" }
  /^shortcuts:[[:space:]]*$/ { in_ss = 1; next }
  !in_ss { next }
  /^[a-zA-Z]/ { in_ss = 0 }
  /^  - name:/ {
    if (name != "") print name "|" verb "|" artifact "|" alias_of "|" repurpose
    name=""; verb=""; artifact=""; alias_of=""; repurpose="false"
    line=$0; sub(/^  - name:[[:space:]]*/, "", line); gsub(/[[:space:]]*#.*$/, "", line); name=line
  }
  /^    verb:/ { line=$0; sub(/^    verb:[[:space:]]*/, "", line); gsub(/[[:space:]]*#.*$/, "", line); verb=line }
  /^    artifact:/ { line=$0; sub(/^    artifact:[[:space:]]*/, "", line); gsub(/[[:space:]]*#.*$/, "", line); gsub(/"/, "", line); artifact=line }
  /^    alias_of:/ { line=$0; sub(/^    alias_of:[[:space:]]*/, "", line); gsub(/[[:space:]]*#.*$/, "", line); alias_of=line }
  /^    repurpose:/ { line=$0; sub(/^    repurpose:[[:space:]]*/, "", line); gsub(/[[:space:]]*#.*$/, "", line); repurpose=line }
  END { if (name != "") print name "|" verb "|" artifact "|" alias_of "|" repurpose }
' "$CATALOG")

if [[ -z "$ROWS_TSV" ]]; then
    fail "CDP01 catalog parses to at least one shortcuts: row"
    test_summary
    exit 1
else
    pass "CDP01 catalog parses to at least one shortcuts: row"
fi

ROW_COUNT=$(echo "$ROWS_TSV" | grep -c . || true)
echo "  (catalog carries ${ROW_COUNT} row(s) -- count-agnostic invariant)"

declare -A CATALOG_NAMES=()

# ---------------------------------------------------------------------------
# Per-row assertions
# ---------------------------------------------------------------------------
i=0
while IFS='|' read -r name verb artifact alias_of repurpose; do
    [[ -z "$name" ]] && continue
    i=$((i + 1))
    CATALOG_NAMES["$name"]=1

    skill_dir="${SKILLS_ROOT}/${name}"
    skill_md="${skill_dir}/SKILL.md"

    # -- name/dir/prefix (applies to EVERY row, thin doorway or repurpose) --
    assert_dir_exists "$skill_dir" "CDP${i}a [${name}] skill directory exists (no orphan row)"

    if [[ "$name" != aid-* ]]; then
        fail "CDP${i}b [${name}] row name carries the aid- prefix"
    else
        pass "CDP${i}b [${name}] row name carries the aid- prefix"
    fi

    if [[ ! -f "$skill_md" ]]; then
        fail "CDP${i}c [${name}] SKILL.md exists at $skill_md"
        continue
    fi
    pass "CDP${i}c [${name}] SKILL.md exists"

    fm_name=$(grep -m1 '^name:' "$skill_md" | sed 's/^name:[[:space:]]*//')
    assert_eq "$fm_name" "$name" "CDP${i}d [${name}] frontmatter name: == directory name == row name"

    if [[ "$repurpose" == "true" ]]; then
        log "CDP${i}e [${name}] repurpose: true row -- body-content assertion exempted (feature-012 owns this body)"
        continue
    fi

    # -- thin-doorway rows: body binds {verb, artifact} + delegates to the engine --
    body=$(cat "$skill_md")

    verb_bind="VERB=\`${verb}\`"
    if echo "$body" | grep -qF "$verb_bind"; then
        pass "CDP${i}e [${name}] body binds VERB=\`${verb}\`"
    else
        fail "CDP${i}e [${name}] body binds VERB=\`${verb}\` -- pattern not found"
    fi

    if [[ -z "$artifact" ]]; then
        artifact_bind='ARTIFACT="" (bare verb)'
    else
        artifact_bind="ARTIFACT=\`${artifact}\`"
    fi
    if echo "$body" | grep -qF "$artifact_bind"; then
        pass "CDP${i}f [${name}] body binds ${artifact_bind}"
    else
        fail "CDP${i}f [${name}] body binds ${artifact_bind} -- pattern not found"
    fi

    if echo "$body" | grep -qF "$ENGINE_REF"; then
        pass "CDP${i}g [${name}] body delegates to ${ENGINE_REF}"
    else
        fail "CDP${i}g [${name}] body delegates to ${ENGINE_REF} -- pattern not found"
    fi
done <<< "$ROWS_TSV"

# ---------------------------------------------------------------------------
# No orphan directory: every GENERATED-marker doorway must have a matching catalog row.
# ---------------------------------------------------------------------------
orphan_found=0
while IFS= read -r d; do
    [[ -z "$d" ]] && continue
    dname=$(basename "$d")
    md="${d}/SKILL.md"
    [[ -f "$md" ]] || continue
    grep -qF "$GENERATED_MARKER" "$md" || continue
    if [[ -z "${CATALOG_NAMES[$dname]:-}" ]]; then
        fail "CDP-ORPHAN [${dname}] generated doorway has no matching catalog row"
        orphan_found=1
    fi
done < <(find "$SKILLS_ROOT" -mindepth 1 -maxdepth 1 -type d | sort)

if [[ "$orphan_found" -eq 0 ]]; then
    pass "CDP-ORPHAN no orphan generated doorway found (every GENERATED-marker dir has a catalog row)"
fi

# ---------------------------------------------------------------------------
# Corroborating oracle: build-shortcut-skills.py --check (byte-level drift detector).
# ---------------------------------------------------------------------------
helper_out=$(cd "$REPO_ROOT" && python3 "$BUILD_HELPER" --check 2>&1)
helper_rc=$?
assert_exit_eq "$helper_rc" 0 "CDP-HELPER build-shortcut-skills.py --check exits 0 (drift-free)"
assert_output_contains "$helper_out" "OK:" "CDP-HELPER --check reports OK (no drift, no orphans)"

echo ""
test_summary
