#!/usr/bin/env bash
# build-kb-index.sh — generate .aid/knowledge/INDEX.md from KB doc frontmatter.
#
# INDEX.md is the RAG (Retrieval-Augmented Generation) connection between agents and
# the KB: every agent task prompt carries INDEX.md so the agent knows what KB doc to
# load for what knowledge. It's composed from each KB doc's `intent:` field
# (see canonical/templates/kb-authoring/frontmatter-schema.md).
#
# Per canonical/templates/kb-authoring/principles.md P3, this script runs LAST in
# any /aid-discover cycle (after all hand-edits land), so the index reflects final
# state.
#
# Usage:
#   bash build-kb-index.sh --root <kb-root> --output <output-path>
#
# Exit codes:
#   0 — success
#   1 — argument error
#   2 — I/O error
#   3 — frontmatter parse error in input

set -eu

ROOT=""
OUTPUT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)   ROOT="$2";   shift 2 ;;
        --output) OUTPUT="$2"; shift 2 ;;
        -h|--help)
            cat <<'HELP_EOF'
build-kb-index.sh — generate .aid/knowledge/INDEX.md from KB doc frontmatter.

Composes the RAG navigation index from each KB doc's `intent:` field.
INDEX.md is the agent-facing self-service map; every task prompt loads it.

Per canonical/templates/kb-authoring/principles.md P3, this script runs LAST
in any /aid-discover cycle so the index reflects final state.

Usage:
  bash build-kb-index.sh --root <kb-root> --output <output-path>

Exit codes:
  0 — success
  1 — argument error
  2 — I/O error
  3 — frontmatter parse error in input
HELP_EOF
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

[[ -n "$ROOT" ]]   || { echo "--root is required" >&2; exit 1; }
[[ -n "$OUTPUT" ]] || { echo "--output is required" >&2; exit 1; }
[[ -d "$ROOT" ]]   || { echo "Root not a directory: $ROOT" >&2; exit 2; }

ROOT="$(cd "$ROOT" && pwd)"
OUT_DIR="$(dirname "$OUTPUT")"
mkdir -p "$OUT_DIR"

TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Helper: extract a single-line YAML field value from frontmatter
# Args: <file> <field-name>
extract_field() {
    local f="$1" field="$2"
    # Only look inside the FIRST --- ... --- block.
    # Symmetric with extract_literal: exit when we leave that block, so a body-level
    # thematic-break `---` cannot re-enter "frontmatter mode" and surface body values.
    awk -v field="$field" '
        BEGIN { in_fm=0 }
        /^---$/ { in_fm = !in_fm; if (NR > 1 && !in_fm) exit; next }
        in_fm && $0 ~ "^"field":" {
            sub("^"field":[[:space:]]*", "")
            print
            exit
        }
    ' "$f"
}

# Helper: extract multi-line YAML literal (|) field
# Args: <file> <field-name>
extract_literal() {
    local f="$1" field="$2"
    awk -v field="$field" '
        BEGIN { in_fm=0; in_field=0; indent=-1 }
        /^---$/ { in_fm = !in_fm; if (!in_fm) exit; next }
        in_fm && in_field {
            # Determine indent on first content line
            if (indent == -1 && /^[[:space:]]+/) {
                match($0, /^[[:space:]]+/)
                indent = RLENGTH
            }
            # Stop when we see a line at lower indent (new field) or top-level
            if (/^[^[:space:]-]/ || /^[a-zA-Z][a-zA-Z0-9_-]*:/) {
                exit
            }
            # Strip leading indent
            sub("^[[:space:]]{" indent "}", "")
            print
            next
        }
        in_fm && $0 ~ "^"field":[[:space:]]*\\|" {
            in_field = 1
            next
        }
    ' "$f"
}

# --- Begin output -----------------------------------------------------------
{
    cat <<EOF
---
kb-category: primary
source: generated
generator: build-kb-index.sh
intent: |
  RAG navigation index — every agent task prompt loads this file so the agent knows
  which KB doc to read for what knowledge. Each entry is the source doc's frontmatter
  intent: field. Regenerated on every /aid-discover cycle.
contracts:
  - "One entry per non-dot, non-recursive KB document under .aid/knowledge/"
changelog:
  - $(date -u +%Y-%m-%d): Generated
---

<!-- AUTO-GENERATED $TS by canonical/scripts/kb/build-kb-index.sh -->
<!-- DO NOT EDIT — regenerate with: bash canonical/scripts/kb/build-kb-index.sh --root .aid/knowledge --output .aid/knowledge/INDEX.md -->

# Knowledge Base Index

> Auto-generated by \`build-kb-index.sh\` from each doc's \`intent:\` frontmatter field.
> Do not edit by hand. Generated at: $TS.

Each entry shows the document name, its \`kb-category:\`, and its declared intent.

EOF

    # Group output by kb-category
    declare -a all_docs

    while IFS= read -r f; do
        all_docs+=("$f")
    done < <(find "$ROOT" -maxdepth 1 -type f -name '*.md' ! -name '.*' | sort)

    if [[ ${#all_docs[@]} -eq 0 ]]; then
        echo "*(no KB docs found at \`$ROOT\`)*"
        echo ""
    fi

    for category in primary meta extension; do
        emitted_header=0
        for f in "${all_docs[@]}"; do
            name=$(basename "$f")
            doc_cat=$(extract_field "$f" "kb-category")
            doc_cat=${doc_cat:-primary}   # default if missing

            if [[ "$doc_cat" == "$category" ]]; then
                if [[ $emitted_header -eq 0 ]]; then
                    case "$category" in
                        primary)   echo "## Primary — load-bearing knowledge" ;;
                        meta)      echo "## Meta — process / ledger (review-exempt)" ;;
                        extension) echo "## Extension — project-specific (outside the declared default seed)" ;;
                    esac
                    echo ""
                    emitted_header=1
                fi

                intent=$(extract_literal "$f" "intent")
                if [[ -z "$intent" ]]; then
                    intent="*(no intent: declared)*"
                fi
                source_field=$(extract_field "$f" "source")
                source_field=${source_field:-hand-authored}

                echo "### [$name](../knowledge/$name)"
                if [[ "$source_field" == "generated" ]]; then
                    generator=$(extract_field "$f" "generator")
                    echo ""
                    echo "*Generated by \`${generator:-unknown}\` — do not hand-edit.*"
                fi
                echo ""
                echo "$intent"
                echo ""
            fi
        done
    done

    echo "---"
    echo ""
    echo "*To regenerate this index, run \`bash canonical/scripts/kb/build-kb-index.sh --root .aid/knowledge --output .aid/knowledge/INDEX.md\`.*"

} > "$OUTPUT"

SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')
LINES=$(wc -l < "$OUTPUT" | tr -d ' ')
echo "✅ Wrote $OUTPUT ($SIZE bytes, $LINES lines)"
