#!/usr/bin/env bash
# build-metrics.sh — generate .aid/generated/metrics.md from disk truth.
#
# Per canonical/templates/kb-authoring/tier-model.md, T3 (Metric) facts are BANNED
# inline in primary KB docs. This script aggregates all numeric measurements
# (line counts, file counts, term counts, severity tallies) into one auto-generated
# file that other docs may reference (but should not duplicate inline).
#
# Usage:
#   bash build-metrics.sh --root <project-root> --output <output-path>
#
# Output:
#   A markdown file with AUTO-GENERATED header + per-section metric tables.
#
# Exit codes:
#   0 — success
#   1 — argument error
#   2 — I/O error (cannot read root or write output)

set -eu

ROOT=""
OUTPUT=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --root)   ROOT="$2";   shift 2 ;;
        --output) OUTPUT="$2"; shift 2 ;;
        -h|--help)
            cat <<'HELP_EOF'
build-metrics.sh — generate .aid/generated/metrics.md from disk truth.

Aggregates T3 numeric facts (line counts, file counts, term counts, severity tallies)
into one auto-generated file. See .agent/aid/templates/kb-authoring/tier-model.md for
why T3 facts are banned inline in primary KB docs.

Usage:
  bash build-metrics.sh --root <project-root> --output <output-path>

Exit codes:
  0 — success
  1 — argument error
  2 — I/O error
HELP_EOF
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

[[ -n "$ROOT" ]]   || { echo "--root is required" >&2; exit 1; }
[[ -n "$OUTPUT" ]] || { echo "--output is required" >&2; exit 1; }
[[ -d "$ROOT" ]]   || { echo "Root not a directory: $ROOT" >&2; exit 2; }

# Resolve absolute paths
ROOT="$(cd "$ROOT" && pwd)"
OUT_DIR="$(dirname "$OUTPUT")"
mkdir -p "$OUT_DIR"

TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# --- KB documents -----------------------------------------------------------
KB_DIR="$ROOT/.aid/knowledge"
KB_DOCS=()
if [[ -d "$KB_DIR" ]]; then
    while IFS= read -r f; do
        KB_DOCS+=("$f")
    done < <(find "$KB_DIR" -maxdepth 1 -type f -name '*.md' | sort)
fi

# --- Canonical skill bodies (this dogfood repo only — guarded) --------------
SKILL_LINES_TABLE=""
SKILL_TOTAL=0
if [[ -d "$ROOT/canonical/skills" ]]; then
    SKILL_FILES=()
    while IFS= read -r f; do
        SKILL_FILES+=("$f")
    done < <(find "$ROOT/canonical/skills" -maxdepth 2 -name 'SKILL.md' | sort)
    if [[ ${#SKILL_FILES[@]} -gt 0 ]]; then
        # Batched line counts: a single `wc -l` over the whole file list instead of
        # one `wc` per SKILL.md. `wc -l file...` prints "count path" per file plus
        # (for >=2 files) a trailing "total" line; take the first field of every
        # non-total line, in argument order, which equals the old per-file
        # `wc -l < "$f" | tr -d ' '` value. `${dir##*/}` / `${f%/*}` replace the
        # basename/dirname forks.
        SKILL_COUNTS=()
        while IFS= read -r n; do
            SKILL_COUNTS+=("$n")
        done < <(wc -l "${SKILL_FILES[@]}" 2>/dev/null | awk '$NF != "total" { print $1 }')
        for i in "${!SKILL_FILES[@]}"; do
            f="${SKILL_FILES[$i]}"
            n="${SKILL_COUNTS[$i]}"
            dir="${f%/*}"
            name="${dir##*/}"
            SKILL_LINES_TABLE+="| \`$name/SKILL.md\` | $n |"$'\n'
            SKILL_TOTAL=$((SKILL_TOTAL + n))
        done
    fi
fi

# --- Begin output -----------------------------------------------------------
{
    cat <<EOF
---
kb-category: meta
source: generated
generator: build-metrics.sh
intent: |
  Aggregated numeric facts (T3 Metric tier per .agent/aid/templates/kb-authoring/tier-model.md):
  line counts, file counts, term counts, severity tallies. Other KB docs reference this
  file instead of inlining the numbers. Regenerated on every /aid-discover cycle.
contracts: []
changelog:
  - $(date -u +%Y-%m-%d): Generated
---

<!-- AUTO-GENERATED $TS by .agent/aid/scripts/kb/build-metrics.sh -->
<!-- DO NOT EDIT — regenerate with: bash .agent/aid/scripts/kb/build-metrics.sh --root . --output .aid/generated/metrics.md -->

# KB Metrics

> Auto-generated by \`build-metrics.sh\`. Do not edit by hand.
> Generated at: $TS

## 1. KB document inventory

EOF

    if [[ ${#KB_DOCS[@]} -gt 0 ]]; then
        echo "| Document | Lines |"
        echo "|----------|-------|"
        kb_total=0
        # Batched line counts: a single `wc -l` over all KB docs instead of one
        # `wc` per doc. `wc -l file...` prints "count path" per file plus (for
        # >=2 files) a trailing "total" line; take the first field of every
        # non-total line, in argument order, which equals the old per-file
        # `wc -l < "$f" | tr -d ' '` value. `${f##*/}` replaces the basename fork.
        KB_COUNTS=()
        while IFS= read -r n; do
            KB_COUNTS+=("$n")
        done < <(wc -l "${KB_DOCS[@]}" 2>/dev/null | awk '$NF != "total" { print $1 }')
        for i in "${!KB_DOCS[@]}"; do
            f="${KB_DOCS[$i]}"
            n="${KB_COUNTS[$i]}"
            name="${f##*/}"
            echo "| $name | $n |"
            kb_total=$((kb_total + n))
        done
        echo "| **TOTAL** | **$kb_total** |"
        echo ""
        echo "KB document count: **${#KB_DOCS[@]}**"
    else
        echo "*(no KB docs found at \`$KB_DIR\`)*"
    fi

    echo ""
    echo "## 2. Canonical skill bodies"
    echo ""

    if [[ -n "$SKILL_LINES_TABLE" ]]; then
        echo "| Skill | Lines |"
        echo "|-------|-------|"
        echo -n "$SKILL_LINES_TABLE"
        echo "| **TOTAL** | **$SKILL_TOTAL** |"
    else
        echo "*(no canonical/skills directory — this is normal for adopters; only the dogfood repo has it)*"
    fi

    # --- Severity tallies (tech-debt) -----------------------------------------
    echo ""
    echo "## 3. Severity tallies"
    echo ""

    if [[ -f "$KB_DIR/tech-debt.md" ]]; then
        td_high=$(grep -cE '\[HIGH\]|^\| H[0-9]+|^\| \*\*H[0-9]+' "$KB_DIR/tech-debt.md" 2>/dev/null || echo 0)
        td_med=$(grep -cE '\[MEDIUM\]|^\| M[0-9]+|^\| \*\*M[0-9]+' "$KB_DIR/tech-debt.md" 2>/dev/null || echo 0)
        td_low=$(grep -cE '\[LOW\]|^\| L[0-9]+|^\| \*\*L[0-9]+' "$KB_DIR/tech-debt.md" 2>/dev/null || echo 0)
        echo "### tech-debt.md"
        echo ""
        echo "| Severity | Count |"
        echo "|----------|-------|"
        echo "| HIGH | $td_high |"
        echo "| MEDIUM | $td_med |"
        echo "| LOW | $td_low |"
        echo ""
    fi

    # --- Glossary term count -----------------------------------------------
    if [[ -f "$KB_DIR/domain-glossary.md" ]]; then
        # Terms are table rows starting with "| **TermName**" where TermName can
        # begin with any non-whitespace character (uppercase letter, lowercase
        # letter, digit, or backtick for code-formatted names). The previous
        # `[A-Z]` constraint undercounted 23 valid terms starting with
        # lowercase / numeric / backtick (e.g., `project-index.md`,
        # `heartbeat_interval`, `workType`).
        terms=$(grep -cE '^\| \*\*[^ ]' "$KB_DIR/domain-glossary.md" 2>/dev/null || true)
        terms=${terms:-0}
        echo "## 4. Domain glossary"
        echo ""
        echo "Term count: **$terms**"
        echo ""
    fi

    # --- Feature inventory counts ------------------------------------------
    if [[ -f "$KB_DIR/feature-inventory.md" ]]; then
        # Match Status TEXT values (not glyphs — per coding-standards.md §13:
        # machine-parsed values are text, glyphs are display-only).
        # Constrain to data rows: line starts with '|', has at least 2 columns
        # before Status, Status text surrounded by spaces inside pipe-delimiters.
        # This excludes legend rows, header rows, separator rows, and body prose.
        # grep -c outputs "N\n" on matches AND exits 1 with no matches; the
        # `|| true` suppresses the failure, and `${var:-0}` defaults empty → 0.
        # This avoids the "0\n0" double-output bug from `|| echo 0`.
        shipped=$(grep -cE '^\|[^|]*\|[^|]*\| Shipped \|' "$KB_DIR/feature-inventory.md" 2>/dev/null || true)
        shipped=${shipped:-0}
        partial=$(grep -cE '^\|[^|]*\|[^|]*\| Partial \|' "$KB_DIR/feature-inventory.md" 2>/dev/null || true)
        partial=${partial:-0}
        pending=$(grep -cE '^\|[^|]*\|[^|]*\| Pending \|' "$KB_DIR/feature-inventory.md" 2>/dev/null || true)
        pending=${pending:-0}
        deprecated=$(grep -cE '^\|[^|]*\|[^|]*\| Deprecated \|' "$KB_DIR/feature-inventory.md" 2>/dev/null || true)
        deprecated=${deprecated:-0}
        echo "## 5. Feature inventory"
        echo ""
        echo "| Status | Count |"
        echo "|--------|-------|"
        echo "| Shipped | $shipped |"
        echo "| Partial | $partial |"
        echo "| Pending | $pending |"
        echo "| Deprecated | $deprecated |"
        echo ""
    fi

    echo "---"
    echo ""
    echo "*End of auto-generated metrics. To add a new metric to this report, edit"
    echo "\`.agent/aid/scripts/kb/build-metrics.sh\`.*"

} > "$OUTPUT"

# Report success
SIZE=$(wc -c < "$OUTPUT" | tr -d ' ')
LINES=$(wc -l < "$OUTPUT" | tr -d ' ')
echo "✅ Wrote $OUTPUT ($SIZE bytes, $LINES lines)"
