#!/usr/bin/env python3
"""build-shortcut-skills.py -- maintainer build helper for the direct-entry shortcut
catalog (feature-003, work-001-lite-aid-skills).

Reads canonical/aid/templates/shortcut-catalog.yml and emits/refreshes the thin-doorway
canonical/skills/aid-<name>/SKILL.md directories, one per non-`repurpose` row. Each
doorway carries minimal frontmatter (name == dir; description with the "State machine:"
line delegating to the engine; allowed-tools; argument-hint) plus a short body that
binds the row's {verb, artifact} and delegates to
canonical/aid/templates/shortcut-engine.md.

`repurpose: true` rows (aid-deploy, aid-monitor, aid-query-kb, aid-ask) are SKIPPED --
they are hand-authored skills (the feature-012 fat pipeline skills aid-deploy/aid-monitor,
plus the v2.1.0 coverage-gap Q&A skills aid-query-kb/aid-ask), never generated or
overwritten here.

Maintainer-only, like run_generator.py: lives beside it under
.claude/skills/generate-profile/scripts/, is NOT under canonical/, and never ships
(architecture.md "Gotchas": "generate-profile is maintainer-only ... do not look for
it in canonical/skills/").

Usage (run from the repo root, matching run_generator.py's own convention):

    python .claude/skills/generate-profile/scripts/build-shortcut-skills.py [--check]

    --check   Verify every generated doorway is already up to date and that no
              stale (marker-tagged) generated directory is left behind; write
              nothing. Exit 1 if anything is missing/stale/orphaned, else 0.

Workflow (feature-003 SPEC "Layers & Components"): after ANY catalog edit, the
maintainer runs THIS helper, then the FULL run_generator.py (never a partial render --
architecture.md "Gotchas": "After any canonical/ edit, run the FULL run_generator.py").

No third-party imports -- stdlib only, matching the renderer's own zero-dependency
convention (technology-stack.md: "The Python renderer and dashboard reader use only
the standard library"). The catalog's YAML is a deliberately restricted subset (a
`version:` scalar + a `shortcuts:` list of flat single-level string/bool/null
mappings), so a small hand-rolled parser below stands in for a real YAML library.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(".")
CATALOG_PATH = REPO_ROOT / "canonical" / "aid" / "templates" / "shortcut-catalog.yml"
SKILLS_ROOT = REPO_ROOT / "canonical" / "skills"

# Closed 8-enum (artifact-schemas.md § Contracts) -- byte-stable, no enum change.
_VALID_TYPES = frozenset({
    "RESEARCH", "DESIGN", "IMPLEMENT", "TEST", "DOCUMENT", "MIGRATE", "REFACTOR", "CONFIGURE",
})

_REQUIRED_FIELDS = ("name", "verb", "artifact", "alias_of", "default_type", "group", "intent")

# Marker embedded in every generated doorway body. Orphan cleanup only ever removes a
# directory whose SKILL.md carries this exact marker -- hand-authored skills (the 15
# shipped pipeline skills, including the 4 repurpose skills aid-deploy/aid-monitor/
# aid-query-kb/aid-ask) never carry it and are therefore never touched, regardless of
# catalog contents.
_GENERATED_MARKER = (
    "<!-- GENERATED by .claude/skills/generate-profile/scripts/build-shortcut-skills.py "
    "from canonical/aid/templates/shortcut-catalog.yml -- DO NOT EDIT BY HAND; edit the "
    "catalog row and re-run the helper, then the full run_generator.py. -->"
)

_ALLOWED_TOOLS = "Read, Glob, Grep, Bash, Write, Edit, Agent"

# Fallback verb for the (should-never-happen) case of an empty `verb` field --
# validate_row does not require `verb` to be non-empty, only present.
_ARGUMENT_HINT_FALLBACK_VERB = "work on"

# Verbs where the plain "what to {verb}" template reads ungrammatically (e.g. a
# compound verb like `show-dashboard`) get a bespoke object-phrase here; every
# other verb uses the natural "what to {verb}".
_ARGUMENT_HINT_OVERRIDES = {
    "show-dashboard": "what dashboard to build",
}


def _argument_hint(row: dict) -> str:
    """Derive a verb-appropriate `argument-hint` for one catalog row.

    Every row already carries a natural-English `verb` (fix, create, change,
    refactor, test, experiment, document, report, prototype, ...), so binding
    it into "what to {verb}" reads correctly for every row without a bespoke
    per-verb map -- "what to fix" / "what to create" / "what to refactor" /
    "what to test" / ... A single hardcoded "what to build" (the prior
    behavior) read wrong for non-create verbs, e.g. aid-fix saying "what to
    build" instead of "what to fix".
    """
    verb = row.get("verb") or _ARGUMENT_HINT_FALLBACK_VERB
    phrase = _ARGUMENT_HINT_OVERRIDES.get(verb, f"what to {verb}")
    return f"[description]  -- {phrase}; runs straight to a graded flattened Lite work"


class CatalogError(Exception):
    """Malformed shortcut-catalog.yml -- a build defect; never guessed past."""


# ---------------------------------------------------------------------------
# Minimal YAML-subset parser (stdlib only; see module docstring for rationale).
# ---------------------------------------------------------------------------

def _strip_comment(line: str) -> str:
    """Strip a trailing ``# ...`` comment, respecting quoted strings."""
    in_squote = False
    in_dquote = False
    for i, ch in enumerate(line):
        if ch == "'" and not in_dquote:
            in_squote = not in_squote
        elif ch == '"' and not in_squote:
            in_dquote = not in_dquote
        elif ch == "#" and not in_squote and not in_dquote:
            return line[:i]
    return line


def _parse_scalar(raw: str):
    """Parse a single YAML scalar value (the restricted subset this catalog uses)."""
    v = raw.strip()
    if v in ("", "null", "~"):
        return None
    if v == "true":
        return True
    if v == "false":
        return False
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        return v[1:-1]
    if v.lstrip("-").isdigit():
        return int(v)
    return v


def parse_catalog(text: str) -> dict:
    """Parse the restricted shortcut-catalog.yml subset.

    Returns ``{"version": <scalar>, "shortcuts": [dict, ...]}``. Each row is a flat
    single-level mapping (the catalog's own field contract has no nesting).
    """
    version = None
    shortcuts: list[dict] = []
    current: dict | None = None
    in_shortcuts = False

    for raw_line in text.splitlines():
        line = _strip_comment(raw_line).rstrip()
        if not line.strip():
            continue

        stripped = line.lstrip()
        indent = len(line) - len(stripped)

        if indent == 0:
            # A new top-level key closes any row in progress.
            if current is not None:
                shortcuts.append(current)
                current = None

            if stripped.startswith("version:"):
                version = _parse_scalar(stripped[len("version:"):])
                in_shortcuts = False
                continue

            if stripped == "shortcuts:" or stripped.startswith("shortcuts: ["):
                in_shortcuts = True
                inline = stripped[len("shortcuts:"):].strip()
                if inline in ("[]", ""):
                    continue
                raise CatalogError(f"unsupported inline 'shortcuts:' value: {stripped!r}")

            in_shortcuts = False
            continue

        if not in_shortcuts:
            # Indented content outside the shortcuts: list -- not this schema's shape.
            continue

        if stripped.startswith("- "):
            if current is not None:
                shortcuts.append(current)
            current = {}
            stripped = stripped[2:]  # the row's first "key: value" shares this line

        if current is None:
            raise CatalogError(f"malformed catalog: row field outside a '- ' row: {raw_line!r}")

        if ":" not in stripped:
            raise CatalogError(f"malformed catalog row line: {raw_line!r}")

        key, _, value = stripped.partition(":")
        current[key.strip()] = _parse_scalar(value)

    if current is not None:
        shortcuts.append(current)

    if version is None:
        raise CatalogError("shortcut-catalog.yml is missing the top-level 'version:' key")

    return {"version": version, "shortcuts": shortcuts}


def load_catalog(path: Path) -> dict:
    if not path.exists():
        raise CatalogError(f"catalog not found: {path}")
    return parse_catalog(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Row validation
# ---------------------------------------------------------------------------

def validate_row(row: dict, index: int) -> None:
    missing = [f for f in _REQUIRED_FIELDS if f not in row]
    if missing:
        raise CatalogError(f"shortcuts[{index}] missing required field(s) {missing}: {row!r}")

    name = row["name"]
    if not isinstance(name, str) or not name.startswith("aid-"):
        raise CatalogError(
            f"shortcuts[{index}] 'name' must be an 'aid-'-prefixed string, got {name!r}"
        )

    default_type = row["default_type"]
    if default_type not in _VALID_TYPES:
        raise CatalogError(
            f"shortcuts[{index}] ({name}) 'default_type' {default_type!r} is not one of "
            f"the closed 8-enum: {sorted(_VALID_TYPES)}"
        )


def validate_unique_names(rows: list[dict]) -> None:
    """Every row's `name` (== skill directory) must be unique across the catalog."""
    seen: dict[str, int] = {}
    for i, row in enumerate(rows):
        name = row.get("name")
        if name in seen:
            raise CatalogError(
                f"duplicate 'name' {name!r}: shortcuts[{seen[name]}] and shortcuts[{i}] "
                "both claim the same skill directory"
            )
        seen[name] = i


# ---------------------------------------------------------------------------
# Doorway rendering
# ---------------------------------------------------------------------------

def render_doorway(row: dict) -> str:
    """Render the full SKILL.md content (frontmatter + body) for one catalog row."""
    name = row["name"]
    verb = row["verb"]
    artifact = row["artifact"] or ""
    intent = row["intent"]
    alias_of = row.get("alias_of")

    title = f"{verb} {artifact}".strip()
    artifact_bind = f"ARTIFACT=`{artifact}`" if artifact else 'ARTIFACT="" (bare verb)'

    frontmatter = (
        "---\n"
        f"name: {name}\n"
        "description: >\n"
        f"  Direct-entry Lite-path shortcut ({intent}) -- skips the aid-describe\n"
        f"  interview/triage. Binds VERB=`{verb}` {artifact_bind} and runs the shared\n"
        "  shortcut engine, producing a fully-graded flattened Lite work that halts for\n"
        "  approval.\n"
        "  State machine: delegated to canonical/aid/templates/shortcut-engine.md\n"
        "  (INTAKE -> CAPTURE -> SPEC -> PLAN -> DETAIL -> GATE -> APPROVAL-HALT).\n"
        f"allowed-tools: {_ALLOWED_TOOLS}\n"
        f'argument-hint: "{_argument_hint(row)}"\n'
        "---\n"
    )

    body_lines = [
        "",
        f"# Shortcut: {title}",
        "",
        _GENERATED_MARKER,
        "",
    ]
    if alias_of:
        body_lines += [
            f"This is a thin alias of `{alias_of}` -- identical `{{verb, artifact}}` "
            "binding, a separate directory (the generator provides no alias/redirect "
            "mechanism; see `shortcut-catalog.yml`'s Topology note).",
            "",
        ]
    body_lines += [
        f"Bind **VERB=`{verb}`**, **{artifact_bind}**, then run the shared engine at "
        "`canonical/aid/templates/shortcut-engine.md`. The engine scaffolds the "
        "flattened Lite work (feature-001 structure), authors REQUIREMENTS -> SPEC -> "
        "PLAN + BLUEPRINT -> DETAIL tasks with reduced capture, runs the per-document "
        "Grading Gates (feature-004), and halts at the FR-10 approval gate. It never "
        "executes. This shortcut's `default_type`/`group`/`alias_of` are its row in "
        "`canonical/aid/templates/shortcut-catalog.yml`.",
        "",
    ]
    body = "\n".join(body_lines)

    return frontmatter + body


# ---------------------------------------------------------------------------
# Orphan detection (marker-gated -- never touches a hand-authored skill dir)
# ---------------------------------------------------------------------------

def find_orphans(current_names: set[str]) -> list[Path]:
    """Generated dirs no longer backed by a catalog row.

    Only ever returns a directory whose SKILL.md carries the ``_GENERATED_MARKER`` --
    hand-authored skills (the 15 shipped pipeline skills, including the 4 `repurpose`
    skills) never carry it and are therefore never candidates, regardless of
    whether their name happens to be absent from the catalog.
    """
    orphans: list[Path] = []
    if not SKILLS_ROOT.is_dir():
        return orphans

    for d in sorted(SKILLS_ROOT.iterdir()):
        if not d.is_dir() or d.name in current_names:
            continue
        skill_md = d / "SKILL.md"
        if not skill_md.is_file():
            continue
        try:
            content = skill_md.read_text(encoding="utf-8")
        except OSError:
            continue
        if _GENERATED_MARKER in content:
            orphans.append(d)

    return orphans


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify doorways are up to date and no orphans remain; write nothing",
    )
    args = parser.parse_args(argv)

    try:
        catalog = load_catalog(CATALOG_PATH)
    except CatalogError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    rows = catalog["shortcuts"]
    try:
        for i, row in enumerate(rows):
            validate_row(row, i)
        validate_unique_names(rows)
    except CatalogError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    generated_rows = [r for r in rows if not r.get("repurpose", False)]
    skipped_repurpose = len(rows) - len(generated_rows)
    current_names = {r["name"] for r in generated_rows}

    drift: list[str] = []
    written = 0

    for row in generated_rows:
        name = row["name"]
        out_dir = SKILLS_ROOT / name
        out_path = out_dir / "SKILL.md"
        content = render_doorway(row)
        encoded = content.encode("utf-8")

        existing = out_path.read_bytes() if out_path.is_file() else None
        if existing == encoded:
            continue

        if args.check:
            drift.append(f"stale or missing: {out_path}")
            continue

        out_dir.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(encoded)
        written += 1

    orphans = find_orphans(current_names)
    if args.check:
        drift += [f"orphaned generated dir: {p}" for p in orphans]
        if drift:
            print("DRIFT DETECTED:")
            for line in drift:
                print(f"  - {line}")
            return 1
        print(
            f"OK: {len(generated_rows)} doorway(s) up to date, "
            f"{skipped_repurpose} repurpose row(s) skipped, 0 orphan(s)."
        )
        return 0

    removed = 0
    for orphan_dir in orphans:
        shutil.rmtree(orphan_dir)
        removed += 1
        print(f"Removed orphaned doorway: {orphan_dir}")

    print(
        f"Generated/refreshed {written} doorway(s) "
        f"({len(generated_rows) - written} already up to date), "
        f"skipped {skipped_repurpose} repurpose row(s), removed {removed} orphan(s)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
